Feature review requests
tensegrity666/x-check-app pull request #24
Opened 2020-09-08 19:51 UTC by zenitfan19

Пока нет получения реальных запросов на ревью через API, заполнил тестовыми данными, ориентируясь на описание сущностей в задании. По дизайну использовал таблицу ant design. Фильтрацию и сортировку прикрутил к тем столбцам, которые на взгляд требуют этого, если что к любому столбцу можно без проблем добавить.
![image](https://user-images.githubusercontent.com/25368210/92521347-c4f00f00-f225-11ea-84ec-9f4b42e97df2.png)

2020-09-08 22:35 UTC, tensegrity666 requested changes
src/pages/requests/constants.js
Из этого файла следует вынести все моковые данные, сейчас непонятно, что из этого останется для продакшена, а что надо будет удалить.
Этот файл не должен находиться в папке pages/

2020-09-08 22:58 UTC, tensegrity666 requested changes

2020-09-08 22:58 UTC, tensegrity666 commented on src/pages/requests/requests.css
> +*::-webkit-scrollbar-thumb {
в проекте используются CSS-модули.
Стили должны находиться в компоненте.  Импортируемый файл должен называться index.

Здесь используется глобальный стиль *, он применится ко всему приложению, но при этом  он находится внутри папки requests/.

2020-09-08 22:58 UTC, tensegrity666 commented on src/pages/requests/components/requests-table.js
> +import React, { Component } from 'react';
Для компонентов есть папка components/, pages/ для организации роутинга, здесь не должно быть стилей компонента, его констант, моковых данных, ассетов.

2020-09-08 22:58 UTC, tensegrity666 commented on src/pages/requests/constants.js
> +    title: 'crossCheckID',
dataIndex и key везде имеют одинаковые значения, может оставить одно какое-то поле, а не дублировать?

2020-09-09 05:06 UTC, Kirillsp1982 approved these changes

2020-09-09 18:35 UTC, zenitfan19 commented on src/pages/requests/requests.css
> +*::-webkit-scrollbar-thumb {
Перенес стили в компонент, подключил как css модуль
![image](https://user-images.githubusercontent.com/25368210/92639335-4f974380-f2e4-11ea-8d63-c3ac26dbe752.png)

2020-09-09 18:36 UTC, zenitfan19 commented on src/pages/requests/components/requests-table.js
> +import React, { Component } from 'react';
Теперь в папке pages чистая страница для роутинга
![image](https://user-images.githubusercontent.com/25368210/92639437-76557a00-f2e4-11ea-9170-e1a35d9f538f.png)
Компонент перенес в папку components
![image](https://user-images.githubusercontent.com/25368210/92639473-85d4c300-f2e4-11ea-8417-9e2a24030679.png)

2020-09-09 18:37 UTC, zenitfan19 commented on src/pages/requests/constants.js
> +    title: 'crossCheckID',
Убрал поле key, по документации позволительно убрать поле key, если все dataIndex уникальные

2020-09-10 17:29 UTC, tensegrity666 approved these changes
удали, пожалуйста, свой локальный файл package-lock.json и сделай npm install.

2020-09-10 18:12 UTC, tensegrity666 approved these changes

2020-09-10 18:12 UTC, tensegrity666 commented on src/components/requests-table/index.js
> +import React, { Component } from 'react';
Слишком большой компонент, объединяющий несколько компонентов с логикой и разметкой. Очень тяжело читать. 
Хорошо было бы разбить его на небольшие компоненты, в которых только разметка и стилизация, никакой своей логики и желательно без стейта, всё попадает к ним через пропсы.
Один компонент-контейнер, в котором находится вся логика и стейт, в нём не должно быть стилей и минимум разметки, он передаёт пропсы.

Классы в реакте должны содержать только методы жизненного цикла, здесь не должно быть такого, как в getColumnSearchProps().

Пустой конструктор для стейта в реакте не нужен, причём линтер должен выдавать на это ошибку.

2020-09-10 18:12 UTC, tensegrity666 commented on src/components/requests-table/index.js
> +    return (
Вот это нормальный отдельный компонет, он должен находиться в отдельном файле и принимать пропсы из компонента-контейнера

```return (
      <div className={styles.reviewRequests}>
        <Н1>Review Requests</Н1>
        <Table
          dataSource={defaultCustomers}
          columns={columnsWithSearch}
          pagination={pagination}
          scroll={{ x: 1200, y: 'calc(100vh - 210px)' }}
        />
      </div>
    );```

2020-09-10 18:12 UTC, tensegrity666 commented on src/components/requests-table/index.js
> +          scroll={{ x: 1200, y: 'calc(100vh - 210px)' }}
{ x: 1200, y: 'calc(100vh - 210px)' }

Скорее всего, это сломается в Сафари, на мобильных и планшетах, на 4К мониторах

2020-09-10 18:12 UTC, tensegrity666 commented on src/components/requests-table/index.js
> +        <SearchOutlined style={{ color: filtered ? '#1890ff' : undefined }} />
{ color: filtered ? '#1890ff' : undefined }

undefined в коде выглядит неприлично, обычно используют null. Здесь можно использовать оператор && вместо тернарного

2020-09-10 18:12 UTC, tensegrity666 commented on src/components/requests-table/index.js
> +              this.searchInput = node;
this.searchInput = node;

такие прямые присвоения это плохая практика и выглядят странно, можно завести поле в стэйте и делать setState()

2020-09-10 18:12 UTC, tensegrity666 commented on src/components/requests-table/index.js
> +      <div className={styles.reviewRequests}>
инлайновый css по всему коду выглядит очень плохо.

здесь не критично, потому что класс всего один, но вообще лучше использовать деструктуризацию:

const { reviewRequests } = styles;
...
className={reviewRequests}

2020-09-11 15:35 UTC, DEnFUrt commented
В компоненте на используются хуки жизненного цикла, желательно переписать его на функциональный компонент. Вынести логику в отдельный "умный компонент", а верстку в другой "глупый компонент", куда будут приходить пропсы из первого компонента. Проще будет тестить и рефакторить при необходимости.

2020-09-16 19:29 UTC, merged